version: "3.7"
services:
  nginx:
    image: nginx:alpine
    container_name: odarena-nginx
    restart: unless-stopped
    ports:
      - 80:80 # change this to 80:80 if you don't have anything running on port 80, otherwise change it to 8080:80
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - odarena-network
    depends_on:
      - app

  app:
    build:
      args:
        user: ix
        uid: 1000
      context: ./.docker/app
      dockerfile: Dockerfile
    image: odarena
    hostname: odarena
    container_name: odarena
    restart: unless-stopped
    ports: 
        - 6001:6001
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/app/php-fpm.ini:/usr/local/etc/php/conf.d/99-app.ini
    networks:
      - odarena-network
    depends_on:
      - database
    #command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

  database:
    image: mariadb:latest
    container_name: odarena-mariadb
    restart: unless-stopped
    ports:
      - 3304:3304
    volumes:
      - odarena-volume:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    networks:
      - odarena-network
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: odarena-phpmyadmin
    restart: unless-stopped
    tty: true
    depends_on:
      - database
    ports:
      - 81:80 # change this to 81:80 if you don't have anything running on port 80, otherwise change it to 8081:80
    environment:
      PMA_HOST: database
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 300M
    networks:
      - odarena-network

  # Redis
  redis:
    image: redis:alpine
    container_name: odarena-redis
    ports:
      - 6379:6379
    networks:
      - odarena-network

networks:
  odarena-network:
    driver: bridge

volumes:
  odarena-volume:
    driver: local