<?php

return [
    'tribeTypes' => [
        'Crew',
        'Gang',
        'Tribe',
        'Band',
        'Rovers',
        'Raiders',
        'Ruffians',
        'Roughnecks',
        'Mongrels',
        'Clan',
        'Scofflaws',
        'Mob',
        'Scoundrels',
        'Rascals',
        'Outlaws',
        'Savages',
        'Vandals',
        'Coterie',
        'Muggers',
        'Brutes',
        'Pillagers',
        'Thieves',
        'Crooks',
        'Junta',
        'Bruisers',
        'Guerrillas',
        'Posse',
        'Herd',
        'Hooligans',
        'Hoodlums',
        'Rapscallions',
        'Scallywags',
        'Knaves',
        'Scamps',
        'Miscreants',
        'Misfits',
        'Good-For-Nothings',
        'Murderers',
        'Vagrants',
        'Brigands',
        'Wildlings',
        'Cutthroats',
        'Lowlifes',
    ],


    'invasionTypes' => [
        'attacked', 
        'raided', 
        'pillaged', 
        'ransacked', 
        'looted', 
        'devastated', 
        'plundered', 
        'sacked', 
        'invaded', 
        'laid waste to',
        'besieged',
        'overran',
        'stormed',
        'conquered',
        'overwhelmed',
        'assaulted',
        'breached',
        'overpowered',
        'subdued',
        'infested',
        'infiltrated',
        'seized'
    ],
    
    'invasionTargets' => [
        'settlement', 
        'village', 
        'town', 
        'hamlet', 
        'plot of unclaimed land', 
        'community', 
        'trading hub', 
        'merchant outpost', 
        'camp',
        'outpost',
        'farmstead',
        'hamlet',
        'cottage',
        'thorp',
        'croft',
        'shanty',
        'cabana',
        'huts',
    ],

];