<?php

# app/config/barbarians.php

return [
    'tribeTypes' => [
        'Crew',
        'Gang',
        'Tribe',
        'Band',
        'Rovers',
        'Raiders',
        'Ruffians',
        'Roughnecks',
        'Mongrels',
        'Clan',
        'Scofflaws',
        'Mob',
        'Scoundrels',
        'Rascals',
        'Outlaws',
        'Savages',
        'Vandals',
        'Coterie',
        'Muggers',
        'Brutes',
        'Pillagers',
        'Thieves',
        'Crooks',
        'Junta',
        'Bruisers',
        'Guerrillas',
        'Posse',
        'Herd',
        'Hooligans',
        'Hoodlums',
        'Rapscallions',
        'Scallywags',
        'Knaves',
        'Scamps',
        'Miscreants',
        'Misfits',
        'Good-For-Nothings',
        'Murderers',
        'Vagrants',
        'Brigands',
        'Wildlings',
        'Cutthroats',
        'Lowlifes',
    ],


    'invasionTypes' => [
        'attacked', 
        'raided', 
        'pillaged', 
        'ransacked', 
        'looted', 
        'devastated', 
        'plundered', 
        'sacked', 
        'invaded', 
        'laid waste to',
        'besieged',
        'overran',
        'stormed',
        'conquered',
        'overwhelmed',
        'assaulted',
        'breached',
        'overpowered',
        'subdued',
        'infested',
        'infiltrated',
        'seized'
    ],
    
    'invasionTargets' => [
        'settlement', 
        'village', 
        'town', 
        'hamlet', 
        'plot of unclaimed land', 
        'community', 
        'trading hub', 
        'merchant outpost', 
        'camp',
        'outpost',
        'farmstead',
        'hamlet',
        'cottage',
        'thorp',
        'croft',
        'shanty',
        'cabana',
        'huts',
    ],

    'settings' => [
        'DPA_CONSTANT' => 27.0,
        'DPA_OVERSHOT' => 1.10,
        'DPA_PER_TICK' => 0.125,
        'DPA_PER_TIMES_INVADED' => 1.5,
        'OPA_MULTIPLIER' => (4/3),
        'SPECS_RATIO_MIN' => 50,
        'SPECS_RATIO_MAX' => 500,
        'CHANCE_TO_HIT_CONSTANT' => 14,
        'LAND_GAIN_MIN' => 300,
        'LAND_GAIN_MAX' => 100,
        'SENT_RATIO_MIN' => 800,
        'SENT_RATIO_MAX' => 1000,
        'CASUALTIES_MIN' => 50,
        'CASUALTIES_MAX' => 100,
        'UNITS_TRAINED_MIN' => 800,
        'UNITS_TRAINED_MAX' => 1200,
        'UNITS_TRAINING_TICKS' => 6,
        'CONSTRUCTION_TIME' => 12,
        'UNIT1_OP' => 3,
        'UNIT2_DP' => 3,
        'UNIT3_DP' => 5,
        'UNIT4_OP' => 5,
        'ONE_IN_CHANCE_TO_SPAWN' => 60,
    ],

];